#!/bin/sh

# Run this script to deploy the app to Heroku.

branch="$(basename "$(git symbolic-ref HEAD)")"
target="${1:-staging}"

git push "$target" "$branch:master" &&
  heroku run rake db:migrate --remote "$target" &&
  heroku restart --remote "$target"
